apiVersion: v1
kind: Secret
metadata:
  name: ecr-refresh-aws
  namespace: prd
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_ME"
  AWS_SECRET_ACCESS_KEY: "REPLACE_ME"
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
