apiVersion: v1
kind: Secret
metadata:
  name: ses-sns-events-secrets
  namespace: prd
type: Opaque
stringData:
  MONGODB_URI: "mongodb://USER:PASSWORD@HOST1,HOST2,HOST3,HOST4/?replicaSet=rs0&authSource=admin"
